image: nikolaik/python-nodejs:python3.7-nodejs10

stages:
  - linting
  - test
  - deploy-dev
  - deploy-qa
  - deploy-prod

linter:
  stage: linting
  tags:
    - aws-runner
  image: python:slim
  script:
    - apk add --no-cache zsh ca-certificates python3 gcc python3-dev musl-dev libxml2-dev libxslt-dev openssl-dev libffi-dev python3-dev py3-pip && pip3 install --upgrade pip setuptools wheel
    - python3 -m ensurepip
    - pip3 install pylint
    - pip3 install -r requirements.txt
    - export EXITVALUE=0
    - zsh -c "pylint --output-format=colorized **/*.py" || export EXITVALUE=1
    # - exit $EXITVALUE

coverage:
  stage: test
  tags:
    - aws-runner
  image: python:slim
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  script:
    - pip install coverage moto mock pytest
    - MIN_COVERAGE=85
    - pip3 install --upgrade pip setuptools wheel
    - pip3 install -r requirements.txt
    - coverage run -m pytest tests/
    - coverage report -m
    - coverage html
    - COVERAGE=$(coverage report -m | grep -i "TOTAL" | awk '{print $4}' | sed 's/%//')
    - if [ "$COVERAGE" -lt "$MIN_COVERAGE" ]; then exit 1; else exit 0; fi
  artifacts:
    expire_in: 7 days
    paths:
      - htmlcov/

dev-deployment:
  stage: deploy-dev
  tags:
    - aws-runner
  only:
    - develop
  before_script:
    - pip install awscli
    - aws configure --profile dev set aws_access_key_id $AWS_ACCESS_KEY_ID_DEV
    - aws configure --profile dev set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_DEV
    - npm config set prefix /usr/local
    - npm install -g serverless@2.25.2
  script:
    - serverless deploy --configFile dev.yml

qa-deployment:
  stage: deploy-qa
  tags:
    - aws-runner
  only:
    - qa
  before_script:
    - pip install awscli
    - aws configure --profile dev set aws_access_key_id $AWS_ACCESS_KEY_ID_QA
    - aws configure --profile dev set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_QA
    - npm config set prefix /usr/local
    - npm install -g serverless@2.25.2
  script:
    - serverless deploy --configFile dev.yml

prod-deployment:
  stage: deploy-prod
  tags:
    - aws-runner
  only:
    - master
  before_script:
    - pip install awscli
    - aws configure --profile prod set aws_access_key_id $AWS_ACCESS_KEY_ID_PROD
    - aws configure --profile prod set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_PROD
    - npm config set prefix /usr/local
    - npm install -g serverless
  script:
    - serverless deploy --configFile prod.yml
