service: docuphase-ig-oauth2

provider:
  name: aws
  runtime: python3.8
  stage: dev #${file(config/${opt:configFile}):STAGE}
  region: us-east-1 #${file(config/${opt:configFile}):REGION}
  #profile: ${self:provider.stage}
  environment: 
    OAUTH2_AUTHENTICATOR_DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    SUPPORT_ENGG_EMAIL: support-engg@yourdomain.com #${file(config/${opt:configFile}):SUPPORT_ENGG_EMAIL}
    #AWS_REGION: ${self:service}-${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.OAUTH2_AUTHENTICATOR_DYNAMODB_TABLE}"

functions:
  create:
    handler: oauth.create
    events:
      - http:
          path: oauth
          method: post
          cors: true

resources:
  Resources:
    OAuth2DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: N
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.OAUTH2_AUTHENTICATOR_DYNAMODB_TABLE}

plugins:
  - serverless-python-requirements
  - serverless-plugin-aws-alerts

custom:
  logRetentionInDays:
    prod: 30
    dev: 7
    qa: 7
  pythonRequirements:
    noDeploy: []
    pythonBin: python3
  alerts:
    stages:
      - prod
    dashboards: false
    nameTemplate: ${self:service}-$[functionName]-$[metricName]-Alarm
    topics:
      alarm: 
        topic: ${self:service}-${self:provider.stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${self:provider.environment.SUPPORT_ENGG_EMAIL}
    alarms:
      - functionErrors