name: Test 1 Service

on: push

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: pip install pylint  # -r requirements.txt
      - run: pylint src/adapter/*.py --rcfile pylintrc --output-format=colorized 